[package]
name = "millegrilles_cryptographie"
version = "2024.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
std = []

[dependencies]

log = "0.4"
rand = { version = "0.8", default-features = false }
uuid = { version = "1.7", features = ["serde", "v4"] }

serde = { version = "1.0.197", default-features = false, features = ["derive"] }
serde-json-core = "0.5"

x509-parser = "0.16.0"
openssl = { version = "0.10.64", features = ["vendored"] }
blake2 = "0.10"
sha2 = "0.10.8"
chacha20poly1305 = "0.10"
#dryoc = { version = "0.5.0" }
##dryoc = { version = "0.4" }
#zeroize = { version = "1.6.0", default-features = false }

multibase = "0.9"
multicodec = "0.1"
multihash = "0.19"
base64 = "0.22"
base64-url = "2.0"

[dev-dependencies]
hex = "0.4.3"
