[package]
name = "millegrilles_cryptographie"
version = "2024.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
std = ['alloc']
alloc = []

[dependencies]
heapless = { version = "0.8", features = ["serde"] }
log = "0.4"
rand = { version = "0.8", default-features = false }
uuid = { version = "1.7", features = ["serde", "v4"] }

# String representations
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
serde-json-core = "0.5"
hex = "0.4.3"
multibase = { version = "0.9", default-features = false }
# multicodec = "0.1"
multihash = { version = "0.19", default-features = false }
base64 = { version = "0.22", default-features = false }
base64-url = { version = "2.0", default-features = false }

# Hashing
blake2 = { version = "0.10", default-features = false }
sha2 = { version = "0.10.8", default-features = false }

# Encryption
# openssl = { version = "0.10.64", features = ["vendored"] }
chacha20poly1305 = { version = "0.10", default-features = false }
#dryoc = { version = "0.5.0" }
##dryoc = { version = "0.4" }
#zeroize = { version = "1.6.0", default-features = false }

# Signature
# ed25519 = { version = "2.2.3", default-features = false }
ed25519-dalek = { version = "2.1", default-features = false }
x25519-dalek = { version = "2.0" }

# x509
# x509-parser = "0.16.0"
x509-cert = { version = "0.2.5", default-features = false, features = ["pem"] }
# x509-cert = { version = "0.2.5" }
# rustls-webpki = { version = "0.102.2", default-features = false }

chrono = { version = "0.4", default-features = false }
