[package]
name = "millegrilles_cryptographie"
version = "2026.4.3"
edition = "2024"

[features]
std = []
alloc = ['std', 'serde_json']
optional-defaults = ['alloc', 'hex/default', 'base64/default', 'multibase/default', 'multihash/default', 'chacha20poly1305/default', 'chrono/now']

# High-level features
x509 = ['openssl', 'x509-parser', 'optional-defaults']
x25519 = ['openssl', 'dryoc', 'optional-defaults']
chiffrage = ['alloc', 'x509', 'rand', 'x25519', 'zeroize', 'flate2']

[dependencies]
heapless = { version = "0.8.0", features = ["serde"] }
# log = { version = "0.4.22"}
tracing = "0.1"
chrono = { version = "0.4.38", default-features = false }

# String representations
serde = { version = "1.0.210", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.128", optional = true }
serde-json-core = "0.5.1"
serde_repr = "0.1.19"
hex = { version = "0.4.3", default-features = false }
base64 = { version =  "0.22.1", default-features = false }
multibase = { version = "0.9.1", default-features = false }
multihash = { version = "0.19.1", default-features = false }

# Hashing
blake2 = { version = "0.10.6", default-features = false }
sha2 = { version = "0.10.9", default-features = false }

# openssl (x509)
openssl = { version = "0.10.66", features = ["vendored"], optional = true }

# Encryption
rand = { version = "0.9.2", optional = true }
dryoc = { version = "0.7.2", optional = true }
chacha20poly1305 = { version = "0.10.1", default-features = false }
# x25519-dalek = { version = "2.0", default-features = false }
zeroize = { version = "1.8.2", optional = true }
flate2 = { version = "1.0.34", optional = true }

# Signature
ed25519-dalek = { version = "2.2.0", default-features = false }

# x509
x509-parser = { version = "0.18.1", optional = true }
