[package]
name = "millegrilles_cryptographie"
version = "2024.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
std = ['alloc']
alloc = ['serde_json', 'openssl', 'hex/default']

[dependencies]
heapless = { version = "0.8", features = ["serde"] }
log = { version = "0.4", features = ["release_max_level_warn"] }
chrono = { version = "0.4", default-features = false }

# String representations
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.114", optional = true }
serde-json-core = "0.5"
serde_repr = "0.1.18"
hex = { version = "0.4", default-features = false }

# Hashing
blake2 = { version = "0.10", default-features = false }
sha2 = { version = "0.10.8", default-features = false }

# openssl
openssl = { version = "0.10.64", features = ["vendored"], optional = true }

# Encryption
chacha20poly1305 = { version = "0.10", default-features = false }
x25519-dalek = { version = "2.0", default-features = false }
#dryoc = { version = "0.5.0" }
##dryoc = { version = "0.4" }
#zeroize = { version = "1.6.0", default-features = false }

# Signature
ed25519-dalek = { version = "2.1", default-features = false }

# x509

[dev-dependencies]
test-log = "0.2.15"
